//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CityLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=unreal
        ///Name=Player
        ///Map=Frontend.umap
        ///LocalMap=Frontend.umap
        ///LocalOptions=?Game=BmGame.RGIFrontend
        ///TransitionMap=Entry
        ///MapExt=umap
        ///EXEName=BmGame.exe
        ///DebugEXEName=DEBUG-BmGame.exe
        ///SaveExt=usa
        ///Port=7777
        ///PeerPort=7778
        ///GameName=Batman: Arkham City
        ///GameNameShort=Bm
        ///
        ///[Engine.Engine]
        ///NetworkDevice=IpDrv.TcpNetDriver
        ///FallbackNetworkDevice=IpDrv.TcpNetDriver
        ///ConsoleClassName=Engine.Console
        ///GameViewportClientClassName=BmGame.RGFxGameViewportClient
        ///LocalPlayerClassName=Engine.LocalP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BmEngine {
            get {
                return ResourceManager.GetString("BmEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Engine.PlayerInput]
        ///MoveForwardSpeed=1200
        ///MoveStrafeSpeed=1200
        ///LookRightScale=375
        ///LookUpScale=-300
        ///MouseSensitivity=30.0
        ///DoubleClickTime=0.250000
        ///bEnableMouseSmoothing=true
        ///Bindings=(Name=&quot;Fire&quot;,Command=&quot;Button bFire | StartFire | OnRelease StopFire&quot;)
        ///Bindings=(Name=&quot;AltFire&quot;,Command=&quot;StartAltFire | OnRelease StopAltFire&quot;)
        ///Bindings=(Name=&quot;MoveForward&quot;,Command=&quot;Axis aBaseY Speed=1.0&quot;)
        ///Bindings=(Name=&quot;MoveBackward&quot;,Command=&quot;Axis aBaseY Speed=-1.0&quot;)
        ///Bindings=(Name=&quot;TurnLeft&quot;,Command=&quot;Axis aBaseX S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BmInput {
            get {
                return ResourceManager.GetString("BmInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Configuration]
        ///BasedOn=..\BmGame\Config\DefaultEngine.ini
        ///
        ///[SystemSettings]
        ///Fullscreen=True
        ///UseVsync=True
        ///AllowD3D10=False
        ///AllowD3D11=False
        ///ResX=1600
        ///ResY=900
        ///EffectsLevel=3
        ///MultisampleMode=FXAA-HI
        ///DynamicLights=True
        ///LensFlares=True
        ///bAllowLightShafts=True
        ///DynamicShadows=True
        ///MotionBlur=True
        ///Distortion=True
        ///Reflections=True
        ///AmbientOcclusion=True
        ///DetailMode=2
        ///MaxShadowResolution=512
        ///IniVersion=6.9
        ///
        ///[Engine.Engine]
        ///bOnScreenKismetWarnings=FALSE
        ///bSubtitlesEnabled=FALSE
        ///PhysXLevel=1
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserEngine {
            get {
                return ResourceManager.GetString("UserEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Configuration]
        ///BasedOn=..\BmGame\Config\DefaultInput.ini
        ///
        ///[Engine.PlayerInput]
        ///IniVersion=6.9
        ///.Bindings=(Name=&quot;W&quot;,Command=&quot;MoveForward | DebugMenuUpPressed | OnRelease DebugMenuUpReleased | Axis aRawLHJoyUp Speed=1.0&quot;, Shift=false, Control=false, Alt=false, bIgnoreShift=false, bIgnoreCtrl=false, bIgnoreAlt=false):META:COM_FORWARD,0,-1,-1,&quot;&quot;,false,true,CI_Movement,CI_LeftStick,CI_LeftStickUp,CI_LeftStickUpAndDown
        ///.Bindings=(Name=&quot;S&quot;,Command=&quot;MoveBackward | DebugMenuDownPressed | OnRelease DebugMenuDow [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserInput {
            get {
                return ResourceManager.GetString("UserInput", resourceCulture);
            }
        }
    }
}
